<a href="https://colab.research.google.com/github/PtrcE/Programming-class/blob/main/Class%20Work/Decemeber_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SESSION 13

PROGRAM 1

In [ ]:
#1st Function
mylist= ['burger','fries','salad','sandwich','pasta']
print(mylist[3])

sandwich


In [ ]:
#2nd Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.append('chips')
print(mylist)


['burger', 'fries', 'salad', 'sandwich', 'pasta', 'chips']


In [ ]:
#3rd Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.insert(1,'candy')
print(mylist)

['burger', 'candy', 'fries', 'salad', 'sandwich', 'pasta']


In [ ]:
#4th Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.pop(4)
print(mylist)

['burger', 'fries', 'salad', 'sandwich']


In [ ]:
#5th Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.pop()
print(mylist)

['burger', 'fries', 'salad', 'sandwich']


In [ ]:
#6th Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.remove('burger')
print(mylist)

['fries', 'salad', 'sandwich', 'pasta']


In [ ]:
#7th Function
mylist= ['burger','fries','salad','sandwich','pasta']
del mylist[3]
print(mylist)

['burger', 'fries', 'salad', 'pasta']


In [ ]:
#8th Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.clear()
print(mylist)

[]


In [ ]:
#9th Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.sort()
print(mylist)

['burger', 'fries', 'pasta', 'salad', 'sandwich']


In [ ]:
#10th Function
mylist= ['burger','fries','salad','sandwich','pasta']
sorted(mylist)

['burger', 'fries', 'pasta', 'salad', 'sandwich']

In [ ]:
#11th Function
mylist= ['burger','fries','salad','sandwich','pasta']
mylist.reverse()
print(mylist)

['pasta', 'sandwich', 'salad', 'fries', 'burger']


In [ ]:
#12th Function
mylist= ['burger','fries','salad','sandwich','pasta']
len(mylist)

5

PROGRAM 2

In [ ]:
import numpy as np
cars = np.array(['GTR', 'Patrol', 'Civic'])
print(cars)

['GTR' 'Patrol' 'Civic']


PROGRAM 3

In [ ]:
import numpy as np
#create 0 dimensional array
arr=np.array(50)
print('Zero dimensional array:' ,arr)

#creat 1 dimensional array
arr1=np.array([10,20,30,40,50])
print('One dimensional array:' ,arr1)

#create 2 dimensional array
arr2=np.array([[2,4,16],[3,9,81]])
print('Two dimensional array: \n', arr2)

arr3=np.array([[[1,1,1,1],[2,2,2,2]],[[3,3,3,3],[4,4,4,4]]])
print('Multi dimensional array: \n',arr3)

Zero dimensional array: 50
One dimensional array: [10 20 30 40 50]
Two dimensional array: 
 [[ 2  4 16]
 [ 3  9 81]]
Multi dimensional array: 
 [[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]]


PROGRAM 4

TURTLE

In [ ]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for ColabTurtle: filename=ColabTurtle-2.1.0-py3-none-any.whl size=7656 sha256=b37f2d093992e999a6d60f383f1a5ced0b7abb13c358d82d8eb669506b094705
  Stored in directory: /root/.cache/pip/wheels/a9/85/dc/29b6b43c4c6c0fe37192ccad65fe2adcef1e52dd24b0eb61fc
Successfully built ColabTurtle


In [ ]:
initializeTurtle()

In [ ]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

import ColabTurtle.Turtle as t 
initializeTurtle()

t.right(90)
t.forward(100)
t.left(90)
t.backward(100)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


PROGRAM 5

In [ ]:
#square
import ColabTurtle.Turtle as t 
initializeTurtle()

t.right(90)
t.forward(100)
t.left(90)
t.backward(100)
t.left(90)
t.forward(100)
t.right(90)
t.forward(100)


PROGRAM 6

In [ ]:
#square loop
import ColabTurtle.Turtle as t
initializeTurtle()


for t in range(4):
  forward(100)
  right(90)
  forward(100)
  right(90)

PROGRAM 7

In [ ]:
#Change color
import ColabTurtle.Turtle as t 
initializeTurtle()

t.color('yellow')
t.right(90)
t.forward(100)
t.left(90)
t.backward(100)
t.left(90)
t.forward(100)
t.right(90)
t.forward(100)



PROGRAM 8

In [ ]:
#Rectangle

import ColabTurtle.Turtle as t 
initializeTurtle()

t.color('pink')
t.right(90)
t.forward(200)
t.left(90)
t.backward(100)
t.left(90)
t.forward(200)
t.right(90)
t.forward(100)

In [ ]:
#color change in all sides 
import ColabTurtle.Turtle as t 
initializeTurtle()

t.color('yellow')
t.right(90)
t.forward(100)
t.color('red')
t.left(90)
t.backward(100)
t.color('blue')
t.left(90)
t.forward(100)
t.color('green')
t.right(90)
t.forward(100)