<a href="https://colab.research.google.com/github/PtrcE/Programming-class/blob/main/Class%20Work/January_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SESSION 15

In [ ]:
#Funtions
def square_root(num):
    return num*num

for i in range(1,11):
  #function call
    result= square_root(i)
    print("Square root of ",i, "=", result)


Square root of  1 = 1
Square root of  2 = 4
Square root of  3 = 9
Square root of  4 = 16
Square root of  5 = 25
Square root of  6 = 36
Square root of  7 = 49
Square root of  8 = 64
Square root of  9 = 81
Square root of  10 = 100


In [ ]:
#lstrip
message = '      Im Patricia'

#removes spaces on the left 
print('Message:', message.lstrip())

Message: Im Patricia


In [ ]:
#rstrip
message = 'Im Patricia    '

#removes spaces on the right
print('Message:', message.lstrip())

Message: Im Patricia    


In [ ]:
#strip
message = '    Im Patricia   '

# remove all whitespaces
print('Message:', message.strip())

Message: Im Patricia


In [ ]:
#If-else 

alphabet= input("Enter a character: ")

if(alphabet=='A' or alphabet=='a' or alphabet=='E' or alphabet =='e' or alphabet=='I'
 or alphabet=='i' or alphabet=='O' or alphabet=='o' or alphabet=='U' or alphabet=='u'):
    print(alphabet, "is a Vowel")
else:
    print(alphabet, "is a Consonant")

Enter a character: A
A is a Vowel


In [ ]:
#if-elif-else

num1 = (int(input('Please put your 1st number: ')))
num2 = (int(input('Please put your 2nd number: ')))

if num1 > num2:
  print('The smaller number is', num2)
elif num1 < num2:
  print('The smaller number is', num1)
else:
  print('Both numbers are equal.')

Please put your 1st number: 3
Please put your 2nd number: 6
The smaller number is 3


In [ ]:
#list type data + for loop

sweets = ["Kit-Kat", "Ice cream", "Bubble Gum", "Gummy Bear"]
 
for s in sweets:
  print(s)

Kit-Kat
Ice cream
Bubble Gum
Gummy Bear


In [ ]:
#dictionary
student= {'Name': 'Patricia', 'ID': 8, 'Course': 'Creative Computing'}
print('Display key-value pairs')
for key, value in student.items():
  print(f"\nKey:{key}")
  print(f"Value:{value}")

student['gender']='Female'
print(student)

Display key-value pairs

Key:Name
Value:Patricia

Key:ID
Value:8

Key:Course
Value:Creative Computing
{'Name': 'Patricia', 'ID': 8, 'Course': 'Creative Computing', 'gender': 'Female'}


In [ ]:
#tuples 
leap_year=(2000,2004,2008,2012)
non_leap_year=(2001,2005,2009,2013)


print('The 4 previous leap years:',leap_year[0:5])
print('The following 4 non leap years:',non_leap_year[0:5])
print('\n')

#concatenate
print('Few list of of leap years and non leap years are: \n',leap_year+non_leap_year)
print('\n')

#repeating the lists by using * function
print(leap_year*3)
print('\n')

#comparing the tuples
print(leap_year==non_leap_year)
print('\n')

#length of each tuple
print(len(leap_year))
print(len(non_leap_year))
print('\n')

#sum the elements
print(sum(leap_year))
print(sum(non_leap_year))
print('\n')

#sorting the elements
print(sorted(leap_year))
print(sorted(non_leap_year))
print('\n')

#swaping tuples
leap_year,non_leap_year=non_leap_year,leap_year
print('The previous non leap years: ',leap_year)
print('The following leap years: ',non_leap_year)




The 4 previous leap years: (2000, 2004, 2008, 2012)
The following 4 non leap years: (2001, 2005, 2009, 2013)


Few list of of leap years and non leap years are: 
 (2000, 2004, 2008, 2012, 2001, 2005, 2009, 2013)


(2000, 2004, 2008, 2012, 2000, 2004, 2008, 2012, 2000, 2004, 2008, 2012)


False


4
4


8024
8028


[2000, 2004, 2008, 2012]
[2001, 2005, 2009, 2013]


The previous non leap years:  (2001, 2005, 2009, 2013)
The following leap years:  (2000, 2004, 2008, 2012)


In [ ]:
#Nested for loop

n=int(input('Enter the number of rows: '))
i=1
while i<=n:
  j=1
  while j<=i:
    print((i*2-1),end=' ') #odd numbers
    j=j+1
  i=i+1
  print()

Enter the number of rows: 5
1 
3 3 
5 5 5 
7 7 7 7 
9 9 9 9 9 


In [ ]:
#string + for loop

count= 0

string= "Mississippi"
chr = "s"

for i in string:
  if i ==chr:
    count +=1

print(count)

4


In [ ]:
#array

import numpy as np
#create 0 dimensional array
arr=np.array(50)
print('Zero dimensional array:' ,arr)

#creat 1 dimensional array
arr1=np.array([10,20,30,40,50])
print('One dimensional array:' ,arr1)

#create 2 dimensional array
arr2=np.array([[2,4,16],[3,9,81]])
print('Two dimensional array: \n', arr2)

#create multi dimensional array
arr3=np.array([[[1,1,1,1],[2,2,2,2]],[[3,3,3,3],[4,4,4,4]]])
print('Multi dimensional array: \n',arr3)

Zero dimensional array: 50
One dimensional array: [10 20 30 40 50]
Two dimensional array: 
 [[ 2  4 16]
 [ 3  9 81]]
Multi dimensional array: 
 [[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]]


In [ ]:


!pip3 install ColabTurtle
from ColabTurtle.Turtle import *


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for ColabTurtle: filename=ColabTurtle-2.1.0-py3-none-any.whl size=7656 sha256=0ec1ce09ee29f548d9ef47bd216b29dd5725d30e19516e3f64d7a87b0a8eac1d
  Stored in directory: /root/.cache/pip/wheels/a9/85/dc/29b6b43c4c6c0fe37192ccad65fe2adcef1e52dd24b0eb61fc
Successfully built ColabTurtle


In [ ]:
#turtle

#color change in all sides 
import ColabTurtle.Turtle as t 
initializeTurtle()

t.color('yellow')
t.right(90)
t.forward(100)
t.color('red')
t.left(90)
t.backward(100)
t.color('blue')
t.left(90)
t.forward(100)
t.color('green')
t.right(90)
t.forward(100)

In [ ]:
#array + nested for loop

import numpy as np

num=[1,5,2,7,22,6,4,2]
num.sort(reverse=True)

print("Sorted in decending order:",num)

Sorted in decending order: [22, 7, 6, 5, 4, 2, 2, 1]
